import streamlit as st
import openai

try:
    st.subheader("Image generation using Open AI's DALL-E")
    input_prompt = st.text_input("Enter your text prompt")
    if input_prompt is not None:
        if st.button("Generate Image"):
            response = openai.Image.create(prompt= input_prompt, n=1, size="512x512")
            image_url = response['data'][0]['url']
            st.image(image_url, caption="Generated by DALL-E")
except:
    st.info("API Key is incorrect. Please enter a correct API Key.")