import streamlit as st
import openai
import os

# try:
#     st.subheader("Image generation using Open AI's DALL-E")
#     input_prompt = st.text_input("Enter your text prompt")
#     openai.api_key = os.getenv("OPENAI_API_KEY")
#     if input_prompt is not None:
#         if st.button("Generate Image"):
#             response = openai.Image.create(prompt= input_prompt, n=1, size="512x512")
#             image_url = response['data'][0]['url']
#             st.image(image_url, caption="Generated by DALL-E")
# except:
#     st.info("API Key is incorrect. Please enter a correct API Key.")

st.subheader("Image generation using Open AI's DALL-E")
openai.api_key = os.getenv("OPENAI_API_KEY")
client = openai.OpenAI()

input_prompt = st.text_input("Enter your text prompt")
if input_prompt != "":
    response = client.images.generate(
    model="dall-e-3",
    prompt=input_prompt,
    size="1024x1024",
    quality="standard",
    n=1,
    )

    image_url = response.data[0].url
    st.image(image_url, caption="Generated by DALL-E", width=512)
